version: '2'

volumes:
  app-volume:
    external: false
  db-volume:
    external: false

services:

  meteor:
    environment:
      MONGO_URL: mongodb://mongod:27017/yas
    build: .
    ports:
     - "20022:22"
     - "3010:3000"
    volumes:
     - app-volume:/opt/meteor/app
    depends_on:
     - mongod

  mongod:
    image: mongo
    ports:
     - "27018:27017"
    volumes:
     - db-volume:/data/db
